"""empty message

Revision ID: 8d7939e6fe4b
Revises: 2db5bb0637a5
Create Date: 2019-11-10 13:26:00.870818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7939e6fe4b'
down_revision = '2db5bb0637a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todos_list_id_fkey', 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key('todos_list_id_fkey', 'todos', 'todolists', ['list_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
